# Generated by Django 4.2.13 on 2024-05-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='account_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='account_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_account',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
