# Generated by Django 4.2.13 on 2024-05-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otts', '0002_party_account_id_party_account_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='account_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='party',
            name='account_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='party',
            name='bank_account',
            field=models.CharField(max_length=100),
        ),
    ]
